Vagrant.configure("2") do |config|
  (1..3).each do |i|
    config.vm.define "vector-node#{i}" do |node|
      node.vm.box = "ubuntu/jammy64"

      node.vm.hostname = "vector-node#{i}"
      node.vm.network "private_network", ip: "192.168.56.#{10 + i}"
      node.vm.provision "shell", path: "../../scripts/provision.sh"

      node.vm.provider "virtualbox" do |vb|
        vb.name = "vector-node#{i}"
        vb.memory = 2048
        vb.cpus = 2
      end
    end
  end

    # Create node 4 separately
    config.vm.define "vector-node4" do |node|
      node.vm.box = "ubuntu/jammy64"

      node.vm.hostname = "vector-node4"
      node.vm.network "private_network", ip: "192.168.56.14"
      node.vm.provision "shell", path: "../../scripts/provision.sh"

      node.vm.provider "virtualbox" do |vb|
        vb.name = "vector-node4"
        vb.memory = 2048
        vb.cpus = 2
      end
    end
  end
