#                                    __   __  __
#                                    \ \ / / / /
#                                     \ V / / /
#                                      \_/  \/
#
#                                    V E C T O R
#                                   Configuration
#
# ------------------------------------------------------------------------------
# Website: https://vector.dev
# Docs: https://vector.dev/docs
# Chat: https://chat.vector.dev
# ------------------------------------------------------------------------------

# Change this to use a non-default directory for Vector data storage:
# data_dir: "/var/lib/vector"
sources:
  syslog_udp:
    type: syslog
    address: "0.0.0.0:514"
    mode: udp

  syslog_tcp:
    type: syslog
    address: "0.0.0.0:514"
    mode: tcp

  from_vector:
    type: vector
    address: "0.0.0.0:9000"

transforms:
  enrich_metadata:
    type: remap
    inputs:
      - syslog_udp
      - syslog_tcp
      - from_vector
    source: |
      .received_at = now()
      .host = get_env_var("HOSTNAME") ?? "collector"
      .log_source = .source

sinks:
  to_console:
    type: console
    inputs:
      - enrich_metadata
    encoding:
      codec: json
    buffer:
      type: disk
      max_size: 524288000      # adjust based on disk availability
      when_full: block      # block to prevent data loss

  to_file:
    type: file
    inputs:
      - enrich_metadata
    path: /var/log/vector/all_logs.log
    encoding:
      codec: json
    compression: none
    buffer:
      type: disk
      max_size: 524288000      # adjust as needed
      when_full: block
