Vagrant.configure("2") do |config|
  (1..3).each do |i|
    config.vm.define "vector-node#{i}" do |node|
      node.vm.box = "ubuntu/jammy64"

      node.vm.hostname = "vector-node#{i}"
      node.vm.network "private_network", ip: "192.168.56.#{10 + i}"

      node.vm.provider "virtualbox" do |vb|
        vb.name = "vector-node#{i}"
        vb.memory = 1024
        vb.cpus = 1
      end
    end
  end
end
